name: Run Python Script on Schedule

on:
  schedule:
    - cron: "0 4 * * *"   # 每天 UTC 时间 4 点执行（需要调整到你的时区）
  workflow_dispatch:      # 可手动触发

jobs:
  run-script:
    runs-on: windows-latest  # 分配的虚拟机环境

    steps:
    - name: Set environment variables from secrets # 配置环境变量
      run: |
        echo "CONFIG_URL=${{ secrets.CONFIG_URL }}" >> $GITHUB_ENV
        echo "GIST_FILENAME=${{ secrets.GIST_FILENAME }}" >> $GITHUB_ENV
        echo "GIST_ID=${{ secrets.GIST_ID }}" >> $GITHUB_ENV
        echo "GIST_TOKEN=${{ secrets.GIST_TOKEN }}" >> $GITHUB_ENV
        echo "SUBSCRIBE_LIST=${{ secrets.SUBSCRIBE_LIST }}" >> $GITHUB_ENV

    - name: Check environment variables # 检查环境变量
      run: |
        Write-Host "CONFIG_URL=$env:CONFIG_URL"
        Write-Host "GIST_FILENAME=$env:GIST_FILENAME"
        Write-Host "GIST_ID=$env:GIST_ID"
        Write-Host "GIST_TOKEN=$env:GIST_TOKEN"
        Write-Host "SUBSCRIBE_LIST=$env:SUBSCRIBE_LIST"

    - name: Checkout code
      uses: actions/checkout@v4  # 使用别人写好的运行脚本

    - name: Set up Python
      uses: actions/setup-python@v4  # 使用别人写好的运行脚本
      with:
        python-version: "3.10"  # 传入脚本的参数

    - name: Install dependencies
      run: |
        pip install controller regex requests json5 PyYAML

    - name: Run my script
      run: |
        python main.py
      env:
        GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
        GIST_ID: ${{ secrets.GIST_ID }}
        GIST_FILENAME: ${{ secrets.GIST_FILENAME }}
        CONFIG_URL: ${{ secrets.CONFIG_URL }}
        SUBSCRIBE_LIST: ${{ secrets.SUBSCRIBE_LIST }}
