name: Run Python Script on Schedule

on:
  schedule:
    - cron: "0 20 * * *"   # 每天 UTC 时间 4 点执行（需要调整到你的时区）
  workflow_dispatch:      # 可手动触发

jobs:
  run-script:
    runs-on: windows-latest  # 分配的虚拟机环境
    environment: ConfigConvert  # 关键：指定使用的环境，才能访问对应的环境级Secret

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # 使用别人写好的运行脚本

    - name: Set up Python
      uses: actions/setup-python@v4  # 使用别人写好的运行脚本
      with:
        python-version: "3.10"  # 传入脚本的参数

    - name: Install dependencies
      run: |
        pip install controller regex requests json5 PyYAML

    - name: Run my script
      run: |
        python main.py
      env:
        PYTHONIOENCODING: utf-8
        ACTIONS_STEP_DEBUG: true
        ACTIONS_RUNNER_DEBUG: true
        GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
        GIST_ID: ${{ secrets.GIST_ID }}
        GIST_FILENAME: ${{ secrets.GIST_FILENAME }}
        CONFIG_URL: ${{ secrets.CONFIG_URL }}
        SUBSCRIBE_LIST: ${{ secrets.SUBSCRIBE_LIST }}
