name: Run Python Script on Schedule

on:
  schedule:
    - cron: "0 4 * * *"   # 每天 UTC 时间 4 点执行（需要调整到你的时区）
  workflow_dispatch:      # 可手动触发

jobs:
  run-script:
    runs-on: windows-latest  # 分配的虚拟机环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # 使用别人写好的运行脚本

    - name: Set up Python
      uses: actions/setup-python@v4  # 使用别人写好的运行脚本
      with:
        python-version: "3.10"  # 传入脚本的参数

    - name: Install dependencies
      run: |
        pip install controller PyYAML regex configparser requests copy urllib json5 json

    - name: Run my script
      run: |
        python main.py
